### PR TITLE
Fix scribify on py3

### PR DESCRIPTION
**Pull request by asottile**
- Renamed 2 tests so they actually run under pytest (lol)
- Fixed the port race under test
- Fix `scribify` function

### CODE REVIEW

**Comment by asottile** [comment]
I tested this interactively and was not able to get logging or scribe lines from errors before this change.  Afterwards I was :)

**Comment by asottile** [comment]
@patricklucas want to take a look at this one too? <3

**Comment by asottile** [comment]
(I'll want a version bump afterwards too)

**Comment by patricklucas** [comment]
+1

**Comment by patricklucas** [comment]
v2.4.2 released.

**Pull request merged**
