### PR TITLE
[WIP] Try using tox-travis package

### PR DESCRIPTION
**Pull request by tiras-j**
It looks like [this](https://github.com/ryanhiebert/tox-travis) might fix the travis build. MIT license, going to try it out on this PR and see what's what.

### CODE REVIEW

**Comment by asottile** [comment]
Note that the problem is that we can't install scribed

**Comment by tiras-j** [comment]
Makes sense that it would be something more complex. Before I got write some bash is there a reason we don't simply pull the repo, configure, and make install it? Seems like it would be fairly straightforward no?

**Comment by ecanzonieri** [comment]
I think nobody has ever really tried. Feel free to make a pr if you wish,

**Comment by tiras-j** [comment]
I might poke around - internally we do some fancy configuration changes for the build, but I doubt we'd need all that for the tests to work since they are testing the interfaces I believe. If I get too bogged down I'll probably not bother though, but that red X is bothering me.

**Pull request closed without merging**
